In [27]:
import torch 
from d2l import torch as d2l 
import pandas as pd 
import numpy as np

### 2.1.8 Exercise

1. Run the code in this section. Change the conditional statement X == Y to X < Y or X >Y, and then see what kind of tensor you can get.

In [2]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


In [10]:
equal = X == Y
equal

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
type(equal)

torch.Tensor

In [7]:
less_than = X < Y
less_than

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
type(less_than)

torch.Tensor

In [8]:
greater_than = X > Y
greater_than

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [13]:
type(greater_than)

torch.Tensor

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [20]:
X = torch.tensor([[[1, 2, 3]], [[4, 5, 6]]]) 
Y = torch.tensor([[[2, 2, 2]]])              
X.shape, Y.shape

(torch.Size([2, 1, 3]), torch.Size([1, 1, 3]))

In [21]:
X * Y

tensor([[[ 2,  4,  6]],

        [[ 8, 10, 12]]])

In [22]:
X + Y

tensor([[[3, 4, 5]],

        [[6, 7, 8]]])

In [23]:
X - Y

tensor([[[-1,  0,  1]],

        [[ 2,  3,  4]]])

In [24]:
X / Y

tensor([[[0.5000, 1.0000, 1.5000]],

        [[2.0000, 2.5000, 3.0000]]])

In [25]:
Y / X

tensor([[[2.0000, 1.0000, 0.6667]],

        [[0.5000, 0.4000, 0.3333]]])

**<h1 align='center'>2.2.5 Exercises</h1>**

1. Try loading datasets, e.g., Abalone from the UCI Machine Learning Repository50 and
inspect their properties. What fraction of them has missing values? What fraction of
the variables is numerical, categorical, or text?

In [28]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data', header=None)
df.columns = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']

missing_values_fraction = df.isnull().mean()
numerical_fraction = df.select_dtypes(include=['float64', 'int64']).shape[1] / df.shape[1]
categorical_fraction = df.select_dtypes(include=['object']).shape[1] / df.shape[1]

missing_values_fraction, numerical_fraction, categorical_fraction

(Sex               0.0
 Length            0.0
 Diameter          0.0
 Height            0.0
 Whole weight      0.0
 Shucked weight    0.0
 Viscera weight    0.0
 Shell weight      0.0
 Rings             0.0
 dtype: float64,
 0.8888888888888888,
 0.1111111111111111)

2. Try indexing and selecting data columns by name rather than by column number. The pandas documentation on indexing51 has further details on how to do this.

In [32]:
df['Height']

0       0.095
1       0.090
2       0.135
3       0.125
4       0.080
        ...  
4172    0.165
4173    0.135
4174    0.205
4175    0.150
4176    0.195
Name: Height, Length: 4177, dtype: float64

3. How large a dataset do you think you could load this way? What might be the limitations? Hint: consider the time to read the data, representation, processing, and memory footprint. Try this out on your laptop. What happens if you try it out on a server?

Ans: Pandas loads the data into the RAM that means pandas wont be able to maintain speed when size of data exceeds available RAM space. In such case it starts using the disk space which significantly slows down the speed and performance may crash down program

In [33]:
%%time
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data', header=None)

CPU times: user 49.2 ms, sys: 7.75 ms, total: 56.9 ms
Wall time: 2.52 s


4. How would you deal with data that has a very large number of categories? What if the category labels are all unique? Should you include the latter?

Ans: For large numbers of categories, we can use the category dtype and consider aggregating or filtering rare categories. For unique category labels, we can treat them as strings or identifiers and exclude them from analysis if they are not meaningful.

5. What alternatives to pandas can you think of? How about loading NumPy tensors from a file52 ? Check out Pillow53 , the Python Imaging Library.

**<h1 align='center'>2.3.13 Exercises</h1>**

1. Prove that the transpose of the transpose of a matrix is the matrix itself: (A>)> = A.

2. Given two matrices A and B, show that sum and transposition commute: A> + B> = (A + B)>.

3. Given any square matrix A, is A + A> always symmetric? Can you prove the result by using only the results of the previous two exercises?

4. We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.

5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

6. Run A / A.sum(axis=1) and see what happens. Can you analyze the results?

7. When traveling between two points in downtown Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?

8. Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?

9. Feed a tensor with three or more axes to the linalg.norm function and observe its output. What does this function compute for tensors of arbitrary shape?

10. Consider three large matrices, say A ∈ R210 ×216, B ∈ R216 ×25 and C ∈ R25 ×214, initialized with Gaussian random variables. You want to compute the product ABC. Is there any difference in memory footprint and speed, depending on whether you compute (AB)C or A(BC). Why?

11. Consider three large matrices, say A ∈ R210 ×216, B ∈ R216 ×25 and C ∈ R25 ×216. Is there any difference in speed depending on whether you compute AB or AC>? Why? What changes if you initialize C = B> without cloning memory? Why?

12. Consider three matrices, say A, B, C ∈ R100×200. Construct a tensor with three axes by stacking [A, B, C]. What is the dimensionality? Slice out the second coordinate of the third axis to recover B. Check that your answer is correct.

**<h1 align='center'>2.4.6 Exercises</h1>**

1. So far we took the rules for derivatives for granted. Using the definition and limits prove the properties for (i) 𝑓 (𝑥) = 𝑐, (ii) 𝑓 (𝑥) = 𝑥𝑛, (iii) 𝑓 (𝑥) = 𝑒𝑥 and (iv) 𝑓 (𝑥) = log 𝑥.

2. In the same vein, prove the product, sum, and quotient rule from first principles.

3. Prove that the constant multiple rule follows as a special case of the product rule.

4. Calculate the derivative of 𝑓 (𝑥) = 𝑥^𝑥 .

5. What does it mean that 𝑓 ′ (𝑥) = 0 for some 𝑥? Give an example of a function 𝑓 and a location 𝑥 for which this might hold.

6. Plot the function 𝑦 = 𝑓 (𝑥) = 𝑥^3 − 1/𝑥 and plot its tangent line at 𝑥 = 1.

7. Find the gradient of the function 𝑓 (x) = 3 (𝑥1)^2 + 5𝑒^(𝑥2).

8. What is the gradient of the function 𝑓 (x) = ‖x‖2? What happens for x = 0?

9. Can you write out the chain rule for the case where 𝑢 = 𝑓 (𝑥, 𝑦, 𝑧) and 𝑥 = 𝑥(𝑎, 𝑏),𝑦 = 𝑦(𝑎, 𝑏), and 𝑧 = 𝑧(𝑎, 𝑏)?

10. Given a function 𝑓 (𝑥) that is invertible, compute the derivative of its inverse 𝑓 −1 (𝑥). Here we have that 𝑓 −1 ( 𝑓 (𝑥)) = 𝑥 and conversely 𝑓 ( 𝑓 −1 (𝑦)) = 𝑦. Hint: use these properties in your derivation.

**<h1 align='center'>2.5.6 Exercises</h1>**

**<h1 align='center'>2.5.6 Exercises</h1>**

**<h1 align='center'>3.1.6 Exercises</h1>**

**<h1 align='center'>3.2.6 Exercises</h1>**

1. Locate full implementations of the above classes that are saved in the D2L library. We strongly recommend that you look at the implementation in detail once you have gained some more familiarity with deep learning modeling.

2. Remove the save_hyperparameters statement in the B class. Can you still print self.a and self.b? Optional: if you have dived into the full implementation of the HyperParameters class, can you explain why?

**<h1 align='center'>3.3.5 Exercises</h1>**