In [1]:
import torch

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

In [7]:
x[2]

tensor(2)

In [8]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [9]:
x[2]

tensor(2)

In [10]:
len(x)

3

In [11]:
x.shape

torch.Size([3])

### Summary
- Scalars are 0th order tensors
- vectors are 1st order tensors
- matrices are 2nd order tensors
- we denote the matrix by bold letters


In [13]:
A = torch.arange(6).reshape(3,2)
A.T 

tensor([[0, 2, 4],
        [1, 3, 5]])

In [14]:
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [16]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T 

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [17]:
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [18]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [19]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone() # Assign a copy of A to B by allocating new memory 
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [20]:
A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]))

In [21]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [22]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [23]:
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### Reduction

In [24]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [27]:
x

tensor([0., 1., 2.])

In [25]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [28]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [29]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [30]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [31]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [32]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [33]:
A.numel()

6

In [34]:
len(A)

2

In [35]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

### Non-Reduction Sum

In [36]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape 

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [37]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])