In [12]:
import torch

In [13]:
x2 = torch.arange(12)
x2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
x1 = torch.arange(12, dtype=torch.float32) # 0 included and ending at n (not included)
x1

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
x1.numel() # shows the total number of elements

12

In [16]:

x1.shape

torch.Size([12])

In [17]:
X = x1.reshape(3,4) # this changes the shape of our tensor 3 rows and 4 columns
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
# size = n
# shape(h, w)
# w = n/h


In [24]:
x1.reshape(3, -1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
torch.zeros((2, 3, 4)) # That means two matrix of 3x4

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [32]:
torch.randn((2,3,4))

tensor([[[-1.8785,  0.5523, -1.1276, -0.3036],
         [ 1.1896,  0.0953,  0.1739, -0.9266],
         [-0.6931, -1.1212,  0.7798,  1.1523]],

        [[ 0.1501, -1.2184, -0.0063, -0.2117],
         [ 0.0578, -0.8338, -1.6489,  1.0253],
         [ 0.6431, -0.2102,  0.6906, -0.2014]]])

In [39]:
torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [41]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [46]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [48]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [49]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [50]:
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [53]:
X[:2, :]

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.]])

In [54]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [56]:
a = torch.tensor([1.0, 2, 4, 8])
b = torch.tensor([2,2,2,2])
a+b, a-b, a*b, a/b, a**b

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [57]:
a,b

(tensor([1., 2., 4., 8.]), tensor([2, 2, 2, 2]))

In [58]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1,2,3,4], [4,3,2,1]])

X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [60]:
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1) # 0 means row wise concatenation and 1 means column wise concatenation

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [61]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [62]:
X.sum()

tensor(66.)

### Broadcasting (Working mechanism)
1. Expand one or both arrays by copying elements along axes with the length 1 so that after this transformation, the two tensors have the elements along axes with legnth 1 so that after this transformation, the two tensors have the same shape 
2. Perform an elementwise operation on the resulting arrays

In [63]:
a = torch.arange(3).reshape((3,1))
a

tensor([[0],
        [1],
        [2]])

In [64]:
b = torch.arange(2).reshape((1,2))
b

tensor([[0, 1]])

In [65]:
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [66]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### Saving the memory

In [67]:
Y = X + Y 
Y

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]])

In [68]:
before = id(Y)
Y = Y + X 
id(Y) == before

False

In [69]:
Z = torch.zeros_like(Y)
print('id{Z}: ',id(Z))
Z[:] = X + Y 
print('id(Z:', id(Z))

id{Z}:  139765255298080
id(Z: 139765255298080


In [70]:
before = id(X) 
X += Y
id(X) == before 

True

In [71]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [73]:
a = torch.tensor([3,5])

In [84]:
a = torch.tensor([3,5])
# a, a.item(), float(a), int(a) 

In [85]:
a

tensor([3, 5])

In [86]:
int(a)

ValueError: only one element tensors can be converted to Python scalars

In [91]:
X

tensor([[ 2.,  4., 10., 12.],
        [13., 17., 21., 25.],
        [28., 30., 32., 34.]])

In [88]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [90]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### Summary

1. Run the code in this section. Change the conditional statement X == Y to X < Y or X >
Y, and then see what kind of tensor you can get.

In [93]:
X == Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [94]:
X < Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [95]:
X > Y

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

2. Replace the two tensors that operate by element in the broadcasting mechanism with
other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [107]:
A = torch.arange(0,3).reshape(3,-1)
A

tensor([[0],
        [1],
        [2]])

In [108]:
B = torch.arange(0,3).reshape(-1,3)
B

tensor([[0, 1, 2]])

In [109]:
A + B

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])

In [126]:
A = torch.arange(0,6).reshape(-1,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [127]:
B = torch.arange(0,4).reshape(-1,4)
B

tensor([[0, 1, 2, 3]])

In [128]:
B + A

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

## Broadcasting problem??

In [129]:
import os 

os.makedirs(os.path.join('..','data'), exist_ok= True)
data_file = os.path.join('..','data','house_tiny.csv')

with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [130]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


## Data Preparation

In [132]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


### Conversion to the tensor format

In [133]:
import torch 

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[nan, 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [nan, 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

### 2.2.5 Exercise

1. Try loading datasets, e.g., Abalone from the UCI Machine Learning Repository50 and
inspect their properties. What fraction of them has missing values? What fraction of
the variables is numerical, categorical, or text?

In [136]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data', header=None)
df.columns = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']

missing_values_fraction = df.isnull().mean()
numerical_fraction = df.select_dtypes(include=['float64', 'int64']).shape[1] / df.shape[1]
categorical_fraction = df.select_dtypes(include=['object']).shape[1] / df.shape[1]

missing_values_fraction, numerical_fraction, categorical_fraction

(Sex               0.0
 Length            0.0
 Diameter          0.0
 Height            0.0
 Whole weight      0.0
 Shucked weight    0.0
 Viscera weight    0.0
 Shell weight      0.0
 Rings             0.0
 dtype: float64,
 0.8888888888888888,
 0.1111111111111111)

2. Try indexing and selecting data columns by name rather than by column number. The pandas documentation on indexing51 has further details on how to do this.

In [137]:
df

Sex  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
...   ..     ...       ...     ...           ...             ...   
4172   F   0.565     0.450   0.165        0.8870          0.3700   
4173   M   0.590     0.440   0.135        0.9660          0.4390   
4174   M   0.600     0.475   0.205        1.1760          0.5255   
4175   F   0.625     0.485   0.150        1.0945          0.5310   
4176   M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
0             0.1010        0.1500     15  
1             0.0485        0.0700      7  
2             0.1415        0.2100      9  
3             0.1140        0.1550     10  
4             0.0395        0.0550      7  
...              ...           ...    ...  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12  

[4177 rows x 9 columns]

3. How large a dataset do you think you could load this way? What might be the limita-tions? Hint: consider the time to read the data, representation, processing, and memory footprint. Try this out on your laptop. What happens if you try it out on a server?